words/urls.py
from django.urls import path

from . import views

app_name = 'words'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

writingbuddy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('words/', include('words.urls')),
    path('admin/', admin.site.urls),
]

words/models.py
from django.db import models

# Create your models here.

words/views.py
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = 'words/index.html'
    
    def get_queryset(self):
        return

class AboutView(generic.TemplateView):
    template_name = 'words/about.html'
    
    def get_queryset(self):
        return

class ContactView(generic.TemplateView):
    template_name = 'words/contact.html'
    
    def get_queryset(self):
        return

words/templates/words/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wordle - About</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'words/style.css' %}">
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Wordle</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:index' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'words:about' %}">About
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row disp">
      <p>Wordle is a small project created by <a href="{% url 'words:contact' %}">Bartu Sivri</a>.</p>
      <p>Wordle is a search engine to help writers find and choose different words for their essays, poems, lyrics and more. Type in the word you would like learn the definition and usage of, find a replacement for or find rhyming words for.</p>
      <p>It uses <a href="https://www.djangoproject.com/">Django</a>, <a href="https://getbootstrap.com/">Bootstrap 4.3</a> and <a href="https://vuejs.org/">Vue.js</a>.</p>

    </div>
  </div>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Wordle 2019</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

words/templates/words/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wordle - Contact</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'words/style.css' %}">
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Wordle</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:about' %}">About</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'words:contact' %}">Contact
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row disp">
      <p>You can find out how to contact me through my <a href="https://github.com/sbartu">GitHub Profile</a> or my <a href="https://www.linkedin.com/in/bartu-sivri-33b5a9188/">LinkedIn Profile</a>.</p>

    </div>
  </div>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Wordle 2019</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

words/templates/words/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wordle - Your Writing Buddy</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'words/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js"></script>
  <script type='text/javascript' src="https://unpkg.com/axios@0.16.1/dist/axios.min.js"></script>
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Wordle</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'words:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'words:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div id="app">
    <div class="container">

      <!-- Widgets Column -->
      <div class="row disp">

        <!-- Search Widget -->
        <div class="card my-11">
          <h5 class="card-header">Wordle it!</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Type a word and press enter..." v-on:keyup="search">
            </div>
          </div>
        </div>
      </div>
      
      <!-- Normal Word Search Results-->
      <div class="row disp">
        <div class="card my-11">
          <h5 class="card-header">Word Dissected</h5>
          <div class="card-body">
            <div id="carouselIndicatorsW" class="carousel slide" data-interval="false">
              <ol class="carousel-indicators">
                <li v-if="words_display.length === 0 || words_not_found" data-target="#carouselIndicatorsW" data-slide-to="0" class="active"></li>
                <li v-else v-for="(item, index) in words_display" :class="{ 'active': index === 0 }" data-target="#carouselIndicatorsW" v-bind:data-slide-to="index"></li>     
              </ol>

              <div class="carousel-inner">
                <div class="row result">
                  <div v-if="words_not_found" class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                      <p>No results were found for the query "[[ given_query ]]".</p>
                    </div>
                  </div>

                  <div v-else-if="start" class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                      <p>Word definition, synonyms, antonyms and example sentences will be displayed here.</p>
                    </div>
                  </div>
  
                  <div v-else v-for="(item, index) in words_display" class="carousel-item" :class="{ 'active': index === 0}">
                    <div class="carousel-caption d-none d-md-block">
                      <div class="bullets">
                        <ul>
                          <li><b>Definition: </b>[[ item.definition ]]</li>
                          <li><b>Part of Speech: </b>[[ item.partOfSpeech ]]</li>
                          <li><b>Synonyms:</b></li>
                            <ul>
                              <li v-for="syn in item.synonyms">[[ syn ]]</li>
                            </ul>
                          <li><b>Antonyms:</b></li>
                            <ul>
                              <li v-for="ant in item.antonyms">[[ ant ]]</li>
                            </ul>
                          <li><b>Examples:</b></li>
                            <ul>
                              <li v-for="exp in item.examples">[[ exp ]]</li>
                            </ul>
                        </ul>
                      </div>
                    </div>
                  </div>

                </div>
              </div>

              <a class="carousel-control-prev" href="#carouselIndicatorsW" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>

              <a class="carousel-control-next" href="#carouselIndicatorsW" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
      </div>

      <!-- Slang Word Search Results-->
      <div class="row disp">
        <div class="card my-11">
          <h5 class="card-header">Slang Definitions</h5>
          <div class="card-body">
            <div id="carouselIndicators" class="carousel slide" data-interval="false">
              <ol class="carousel-indicators">
                <li v-if="urban_display.length === 0 || urban_not_found" data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                <li v-else v-for="(item, index) in urban_display" :class="{ 'active': index === 0 }" data-target="#carouselIndicators" v-bind:data-slide-to="index"></li>     
              </ol>

              <div class="carousel-inner">
                <div class="row result">
                  <div v-if="urban_not_found" class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                      <p>No results were found for the query "[[ given_query ]]".</p>
                    </div>
                  </div>

                  <div v-else-if="start" class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                      <p>Slang definitions will be displayed here.</p>
                    </div>
                  </div>
  
                  <div v-else v-for="(item, index) in urban_display" class="carousel-item" :class="{ 'active': index === 0}">
                    <div class="carousel-caption d-none d-md-block">
                      <p>[[ item.definition ]]</p>
                    </div>
                  </div>

                </div>
              </div>

              <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
      </div>


      <!-- Rhyming Words Search Results-->
      <div class="row disp">
        <div class="card my-11">
          <h5 class="card-header">Rhyming Words</h5>
          <div class="card-body">
            <p v-if="rhymes_not_found">No results were found for the query "[[ given_query ]]".</p>
            <p v-else-if="rhymes_display.length === 0">Possible list of rhyming words will displayed here.</p>
            <ul v-else>
              <li v-for="item in rhymes_display">[[ item ]]</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  
  </div>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Wordle 2019</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type='text/javascript' src="{% static 'words/config.js' %}"></script>
  <script type='text/javascript' src="{% static 'words/writify_script.js' %}"></script>

</body>

</html>